version: '3.8'

services:
  ecf_db:
    image: mysql:8.0
    container_name: ecf_db
    restart: always
    environment:
      MYSQL_DATABASE: ecf_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: ecf_db
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - .:/docker-entrypoint-initdb.d
