version: "3.8"

services:
  ecf_db:
    image: mysql:8.0
    container_name: ecf_db
    restart: always
    environment:
      MYSQL_DATABASE: ecf_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: ecf_db
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - .:/docker-entrypoint-initdb.d

  test_ecf_db:
    image: mysql:8.0
    container_name: test_ecf_db
    restart: always
    environment:
      MYSQL_DATABASE: test_ecf_db
      MYSQL_ROOT_PASSWORD: testrootpassword
      MYSQL_USER: test_ecf_db
      MYSQL_PASSWORD: test_password
    ports:
      - "3308:3306"
    volumes:
      - .:/docker-entrypoint-initdb.d
